import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import '../constants/app_constants.dart';

class NotificationService {
  NotificationService._();
  static final NotificationService instance = NotificationService._();

  final FlutterLocalNotificationsPlugin _plugin = FlutterLocalNotificationsPlugin();
  bool _initialized = false;

  Future<void> init() async {
    if (_initialized) return;

    const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosInit = DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );

    await _plugin.initialize(
      const InitializationSettings(android: androidInit, iOS: iosInit),
    );

    // Android 13+ permission
    final android = _plugin.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    await android?.requestNotificationsPermission();
    await android?.requestExactAlarmsPermission();

    _initialized = true;
  }

  NotificationDetails get _details => const NotificationDetails(
        android: AndroidNotificationDetails(
          AppConstants.notifChannelId,
          AppConstants.notifChannelName,
          channelDescription: AppConstants.notifChannelDesc,
          importance: Importance.high,
          priority: Priority.high,
        ),
        iOS: DarwinNotificationDetails(),
      );

  Future<void> scheduleAt({
    required int id,
    required String title,
    required String body,
    required DateTime when,
    String? payload,
  }) async {
    if (when.isBefore(DateTime.now())) return;
    await _plugin.zonedSchedule(
      id,
      title,
      body,
      tz.TZDateTime.from(when, tz.local),
      _details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      payload: payload,
    );
  }

  Future<void> showNow({
    required int id,
    required String title,
    required String body,
    String? payload,
  }) async {
    await _plugin.show(id, title, body, _details, payload: payload);
  }

  Future<void> cancel(int id) async => _plugin.cancel(id);

  Future<void> cancelAll() async => _plugin.cancelAll();

  /// Schedule the standard 30/14/7/1-day reminder set for an expiring item.
  Future<void> scheduleExpiryReminders({
    required String baseId,
    required String title,
    required String body,
    required DateTime expiry,
  }) async {
    for (final daysBefore in AppConstants.reminderDaysBefore) {
      final when = expiry.subtract(Duration(days: daysBefore));
      // 9:00 local time on that day
      final at = DateTime(when.year, when.month, when.day, 9);
      final id = ('$baseId-$daysBefore').hashCode;
      await scheduleAt(
        id: id,
        title: title,
        body: '$body — $daysBefore zile rămase',
        when: at,
      );
    }
  }

  /// Schedule the next [maxOccurrences] notifications for a custom recurring
  /// reminder. Returns the IDs that were scheduled — store them if you want
  /// to cancel later. We hash from `baseId-occurrenceIndex` so ids are stable.
  Future<List<int>> scheduleCustomRecurring({
    required String baseId,
    required String title,
    required String body,
    required List<DateTime> occurrences,
  }) async {
    final ids = <int>[];
    for (var i = 0; i < occurrences.length; i++) {
      final when = occurrences[i];
      if (when.isBefore(DateTime.now())) continue;
      final id = ('$baseId-occ-$i').hashCode;
      await scheduleAt(id: id, title: title, body: body, when: when);
      ids.add(id);
    }
    return ids;
  }

  /// Cancels a band of ids previously generated by [scheduleCustomRecurring]
  /// for a given baseId. We don't track them in storage, so we re-derive.
  Future<void> cancelCustomRecurring({
    required String baseId,
    int upToOccurrences = 100,
  }) async {
    for (var i = 0; i < upToOccurrences; i++) {
      final id = ('$baseId-occ-$i').hashCode;
      await cancel(id);
    }
  }
}
